name: Semantic Versioning Tagging

on:
  push:
    branches:
      - main   

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tagging script
        run: bash ./vue-project/commitScript/semServScript.sh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new tag
        run: git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
