name: Semantic Versioning Tagging

on:
  workflow_run:
    workflows: ["Build Project"]
    types:
      - completed

jobs:
  tagging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tagging script
        run: bash ./vue-project/commitScript/semServScript.sh

      - name: Push new tag
        run: git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
