name: tests


on:
  push:                 
    branches:
      - '**'
  pull_request:         
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./vue-project

      - name: Run Unit Tests
        run: npm run test:unit
        working-directory: ./vue-project
